name: magcloud_app
description: Your daily heart-listener, MagCloud
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+20230717001

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  intl:
  flutter:
    sdk: flutter
  retrofit: '>=4.0.0 <5.0.0'
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.3
  get: ^4.6.5
  get_it:
  json_annotation:
  shared_preferences:
  http:
  sign_in_with_apple: ^4.3.0
  firebase_messaging: ^14.6.3
  firebase_core: ^2.14.0
  flutter_local_notifications: ^14.1.1
  google_sign_in: ^6.1.4
  device_info: ^2.0.3
  sqflite: ^2.2.8+4
  image_picker: ^0.8.9
  cached_network_image: ^3.2.3
  sprintf:
  package_info_plus: ^4.0.2
  rainbow_color: ^2.0.1
  webview_javascript_bridge:
  webview_flutter:
  toggle_switch: ^2.1.0
  launch_review: ^3.0.1
  sentry_flutter: ^7.8.0
  scrolls_to_top: ^2.1.0
  firebase_crashlytics: ^3.3.3
  flutter_dialogs: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: ^2.4.6
  json_serializable:
  flutter_native_splash: ^2.3.1
  flutter_oss_licenses: ^2.0.1

flutter_native_splash:
  color: "#E7E5E4"
  image: assets/images/magcloud.png
  android_12:
    color: "#E7E5E4"
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/apple_23px.png
    - assets/images/google_23px.png
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
    - family: KyoboHandWriting
      fonts:
        - asset: assets/fonts/KyoboHandwriting2021sjy.ttf
    - family: KyoboHandWriting2019
      fonts:
        - asset: assets/fonts/KyoboHandwriting2019.ttf
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansTTF/GmarketSansTTFMedium.ttf
        - asset: assets/fonts/GmarketSansTTF/GmarketSansTTFBold.ttf
          weight: 700
        - asset: assets/fonts/GmarketSansTTF/GmarketSansTTFLight.ttf
          weight: 300
