// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtQPCNYqiOK2KMZteZ0YOy_QvSkovX61k',
    appId: '1:218693469610:web:001de531ac8c9f4de257d3',
    messagingSenderId: '218693469610',
    projectId: 'magcloud-c3867',
    authDomain: 'magcloud-c3867.firebaseapp.com',
    storageBucket: 'magcloud-c3867.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdcupu88DuAmdddSTlHxnapSBLWeNewG0',
    appId: '1:218693469610:android:44330292d034b9cce257d3',
    messagingSenderId: '218693469610',
    projectId: 'magcloud-c3867',
    storageBucket: 'magcloud-c3867.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhkIlwCoTf1QKKT4u-tAhfGjoJd9W8Sc0',
    appId: '1:218693469610:ios:eca37b9c599146b6e257d3',
    messagingSenderId: '218693469610',
    projectId: 'magcloud-c3867',
    storageBucket: 'magcloud-c3867.appspot.com',
    androidClientId: '218693469610-08lcnsjm529pr9ht3dk9u2hdc0b0pfae.apps.googleusercontent.com',
    iosClientId: '218693469610-2mf21gapn3hloaemktlopg1gihgc4i2c.apps.googleusercontent.com',
    iosBundleId: 'co.bearus.magcloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhkIlwCoTf1QKKT4u-tAhfGjoJd9W8Sc0',
    appId: '1:218693469610:ios:e99fff227aa966f9e257d3',
    messagingSenderId: '218693469610',
    projectId: 'magcloud-c3867',
    storageBucket: 'magcloud-c3867.appspot.com',
    androidClientId: '218693469610-08lcnsjm529pr9ht3dk9u2hdc0b0pfae.apps.googleusercontent.com',
    iosClientId: '218693469610-ev1nmk1e2vt6v7bgtg540gj7tg8rmfjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.magcloudApp.RunnerTests',
  );
}
